---
title: "RWorksheet_Sison#3A"
output:
  pdf_document: default
  html_document: default
date: "2024-09-30"
---

USING VECTORS
LETTERS
A.
LETTERS <-c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z")
first_eleven_letters <-LETTERS[1:11]
first_eleven_letters

B.
alphabet <- LETTERS
odd_letters <- alphabet[c(TRUE, FALSE)]
odd_letters

c.
vowels <- c("A", "E", "I", "O", "U")
vowels

letters
D.
small_letters <- c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u" ,"v" ,"w", "x", "y", "z")
last_five <-small_letters[22:26]
last_five

E.
small_letters
fifteen_twentyfour <- small_letters [15:24]
fifteen_twentyfour

2.
avg_temperatures <- c(42, 39, 34, 34, 30, 27)
avg_temperatures

A.
city <- c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City")
city

B.
temp <- c(42, 39, 34, 34, 30, 27)
temp

C.
comb <- data.frame (city = c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City"), temp = c(42, 39, 34, 34, 30, 27))
comb

D.
df <- data.frame (City = c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City"),
Temperature = c(42, 39, 34, 34, 30, 27))
names(df) <- c("City", "Temperature")
print(df)

E. 
str(df)

F.
rows_3_and_4 <- df[3:4,]
rows_3_and_4

G.
highest_temp_city <- df[which.max(df$Temperature),]
lowest_temp_city <- df[which.min(df$Temperature),]
highest_temp_city
lowest_temp_city

USING MATRICES
2. 
matrix(c(5, 6, 7, 4, 3, 2, 1, 2, 3, 7, 8,9), nrow=2)
matrix(data = c(3, 4, 5, 6, 7, 8), 3, 2)
diag(1, nrow =6, ncol =5)
diag (6)

A.
values <- c(1:8, 11:14)
matrix_4by3 <- matrix (values, nrow = 3, ncol =4)
matrix_4by3

B.
matrix_multiplied <- matrix_4by3*2
matrix_multiplied 

C.
row2 <- matrix_4by3 [2, ]
row2

D.
d_result <- matrix_4by3[1:2, 3:4]
d_result

E.
e_result <- matrix_4by3[3, 2:3]
e_result

F.
f_result <- matrix_4by3[, 4]
f_result

G.
rownames(matrix_multiplied) <- c("isa", "dalawa", "tatlo")
colnames(matrix_multiplied) <- c("uno", "dos", "tres", "kwatro")
matrix_multiplied

H.
dim(matrix_4by3) <- (2, 6)
matrix_4by3

3.
#1
array_dta <- array(c(1:24), c(3,4,2))
array_dta

dim(array_dta)

length(array_dta)

#2
vectorA <- c(1:24)

an_Array <- array(vectorA, dim = c(3, 4, 2))
an_Array

#3A
values <- rep(c(1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1), times = 2)
array_data <- array(values, dim = c(2, 4, 3))
array_data

#3B
dim(array_data)

#3C
dimnames(array_data) <- list(c("a", "b",), c("A", "B", "C", "D"),c("1st-Dimensional Array", "2nd-Dimensional Array", "3rd-Dimensional Array))

array_data